### ISSUE TITLE
V2.0.0 Release (Includes breaking changes)

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/asset-share-commons#475]
Here's a list of things we should do for v2.0.0 release

- [x] Increase min AEM Version to 6.5.0, as this is the min version that contains the DownloadBinary classes required for AEM as a Cloud Service, direct serving from Blobstore (#505)
    ~Increase min AEM version to 6.4.3 (#474) (moved to 6.4.3 for Core Component 2.8.0 support; Does not appear there is a 6.4.4 uber jar so dropped to 6.4.3)~ 
- [x] Increase Core Components dependency to v2.8.0 (#474)
- [x] Use v2 of Core Components for all sling:resourceSuperTypes (#474 )
- [x] Split sample content pages to new ui.content.sample project
- [x] Move javascript (especially semanticUI) into a new ui.frontend project (#317)
- [x] Remove deprecated features (DM Hybrid, deprecated OSGi Services, etc.)
    * Probably leave Legacy Asset Renditions toggle for now 
- [ ] Compatibility with Adobe Experience Manager as a Cloud Service
  - [x] Update maven project structure (All and Mutable/Immutable)
  - [x] Dispatcher module with ASC rules
  - [x] Move all content from ui.apps not in /apps to ui.content project 
  - [x] Integrate with Async Download Framework
  - [x] Asset Renditions should serve from Blob store directly. (Update #505  to use internal sling includes rather than BinaryDownload)
  - [x] Move to using Repo Init (#506)
  - [x] Provide a way for Dialogs to detect the Oak index being used to determine indexed properties (for Dialog datasources) 
  - [ ] Update documentation/sample-project (including opening SMTP via support request)
  - [x] Double check OSGi configs?
  - [x] Come up with plan for how to handle ui.sample content (remove from all package)
  - [x] Update to v2 of Core Comps where possible and add missing Core Cmps proxy
- [x] Align w/ Cloud Manager quality gates (#494)

Stretch goals:

- [ ] Investigate use to CSS var to theme
- [ ] Add aem-analyer project
- [ ] Move to Spectrum CSS
- [ ] Consolidate ui.content.sample to a single site (and toggled Policy for light/dark)
- [ ] Ensure sorting of case-insensitive strings is performant (or guide users to be aware if it won't be/don't let them pick slow sorting if indexes arent configured to support)(#508)
 
What else?

**Comment by godanny86** [comment]
* Compatibility with Adobe Experience Manager as a Cloud Service
